### ISSUE TITLE
Couldn't detect input encoding on Windows

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-addresses#40]
I must have read too much into a [few](https://github.com/input-output-hk/cardano-addresses/search?q=windows&type=Code) [hints](https://github.com/input-output-hk/cardano-addresses/commit/045761a375b3dd7c9ec45ee0ab73feaf4f2aaa82) of windows support, when determining feasibility of [using the tool from the Daedalus main process ](https://github.com/input-output-hk/daedalus/pull/2041). I'm not really in a position to debug, so would appreciate any help in understanding feasibility of the linked use-case. 

Win10
``` console
echo "Ae2tdPwUPEZ6ocSdVwf4ncX6RwJbfxzz2apqt5qoQGsEcbn3XkXGo79GfEC" | cardano-address address inspect
user error (Couldn't detect input encoding? Data on stdin must be encoded as bech16, bech32 or base58.)

echo "DdzFFzCqrhsmpr7JDY5JpDkXDcNLEYiSxyYPsCLE2sCpNxy19jiuJak98ac2Kep157PAyDpFQ4D5GZgukPhmfTFMU6ox3UpNp6iXf1sh" | cardano-address address inspect
user error (Couldn't detect input encoding? Data on stdin must be encoded as bech16, bech32 or base58.)
```
Ubuntu 18.04
``` console
echo "Ae2tdPwUPEZ6ocSdVwf4ncX6RwJbfxzz2apqt5qoQGsEcbn3XkXGo79GfEC" | cardano-address address inspect
{
    "stake_reference": "none",
    "address_style": "Icarus",
    "address_root": "6431c0baa7132ad66b05be0590e47f4e4ef52a52a22db1e43cd7f570",
    "network_tag": null
}

echo "DdzFFzCqrhsmpr7JDY5JpDkXDcNLEYiSxyYPsCLE2sCpNxy19jiuJak98ac2Kep157PAyDpFQ4D5GZgukPhmfTFMU6ox3UpNp6iXf1sh" | cardano-address address inspect
{
    "stake_reference": "none",
    "address_style": "Byron",
    "address_root": "3d7e904aba4ee1e21b2c3ebb77267c987e2c3a0ccde969a93ae617ae",
    "derivation_path": "581c354a2abbc5db82403cf5dca3a9bbf9121d5c83284c95d9e4aa264915",
    "network_tag": null
}
```

**Comment by rhyslbw** [comment]
Tested from the context of Daedalus Bridge:

![Screenshot from 2020-07-01 01-23-38](https://user-images.githubusercontent.com/303881/86144892-9aa11780-bb39-11ea-958d-4cbcad730b9f.png)

**Comment by KtorZ** [comment]
I believe this is because of an untrimmed `\r` on Windows. Will fix.

**Comment by KtorZ** [comment]
Fixed in a5c9b203206f4bde54a0598785889884004a2ca3

**Comment by rhyslbw** [comment]
Curiously, this [still fails](https://github.com/input-output-hk/daedalus/pull/2041#issuecomment-653060008.) with the same error when [executing within a Node.js child process](https://github.com/input-output-hk/daedalus/blob/feature/cardano-addresses-integration/source/main/ipc/introspect-address.js#L22)
 

@rvl ran into another [platform specific bug](https://github.com/input-output-hk/cardano-addresses/issues/41)

**Comment by rhyslbw** [comment]
Just updated the [Daedalus code ](https://github.com/input-output-hk/daedalus/blob/feature/cardano-addresses-integration/source/main/ipc/introspect-address.js#L21-L40)to use a `spawn`ed process, although it just hangs. Reproducible via via the Daedalus nix-shell on linux:

```console
[nix-shell:~/code/iohk/daedalus]$ cardano-address address inspect
37btjrVyb4KG5pZKzLb6SAKtkBeKC99E6shTz874jhgcEjPRrxafJG96hP5w7xW3xwjoWxPQNZyvQ8K4RG6awvCuUcjX5DCJQRA3C9Air5bkbSeBSj
^C

[nix-shell:~/code/iohk/daedalus]$ echo 37btjrVyb4KG5pZKzLb6SAKtkBeKC99E6shTz874jhgcEjPRrxafJG96hP5w7xW3xwjoWxPQNZyvQ8K4RG6awvCuUcjX5DCJQRA3C9Air5bkbSeBSj | cardano-address address inspect
{
    "stake_reference": "none",
    "address_style": "Byron",
    "address_root": "f3bc1b4dcd320af11686c03f144d2886e4b6719d34105d5d0d69dd5e",
    "derivation_path": "581cececdc43d62416a06a2e6ca422ea8d434cc488e6a0b0575703aa56d4",
    "network_tag": 459045235
}
```

**Comment by rhyslbw** [comment]
This is still not working with https://github.com/input-output-hk/cardano-addresses/commit/dc729b0ba5ba112ee2bfe471c4df947ea7c76f28. I have the same outcome using both the [available binary](https://github.com/input-output-hk/cardano-addresses/actions/runs/164971086) and in the Daedalus nix-shell.

@rvl any ideas?
